swagger: '2.0'
info:
  title: Contoso
  description: HR MCP Server Specification, YAML for streamable MCP support in Copilot Studio
  version: 1.0.0
host: [Connect via browser host name of your dev tunnel]
basePath: /
schemes:
  - https
paths:
  /mcp:
    post:
      summary: HR MCP Server
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: InvokeMCP
      responses:
        '200':
          description: Success
